CC := gcc -lpthread -lsqlite3
Target := client
Modules += main Start Pass my_scanf Select_func interface func/*
Allobjs := main/src/*.o Start/src/*.o Pass/src/*.o my_scanf/src/*.o Select_func/src/*.o interface/src/*.o func/*/src/*.o
